# Generated by Django 4.1.4 on 2023-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="major",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="university",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="image",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="major",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="university",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
