# Generated by Django 4.1.4 on 2023-02-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_studentprofile_address_studentprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
